config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :articles
  resources :users, except: [:new]
  resources :categories, except: [:delete]

end

app/models/article.rb
class Article < ActiveRecord::Base

    belongs_to :user

	validates :title, 
        presence: true, 
        length: { 
            minimum: 3,
		    maximum: 50
        }

	validates :description, 
        presence: true, 
        length: {
		    minimum: 10,
		    maximum: 300
	    }

    validates :user_id,
        presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base

    validates :name,
        presence: true,
        length: {
            minimum: 3,
            maximum: 25
        },
        uniqueness: {
            case_sensitive: false
        }

    before_save {
        self.name = name.downcase
    }
end

app/models/user.rb
class User < ActiveRecord::Base

    has_many :articles, dependent: :destroy
    has_secure_password

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :username,
        presence: true,
        length: {
            minimum: 3,
            maximum: 25
        },
        uniqueness: {
            case_sensitive: false
        }

    validates :email,
        presence: true,
        length: {
            maximum: 50
        },
        format: {
            with: VALID_EMAIL_REGEX
        },
        uniqueness: {
            case_sensitive: false
        }

    before_save {
        self.email = email.downcase
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
        flash[:danger] = "You must be logged in to perform that action."
        redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    before_action :require_user, only: [:new, :create, :edit, :update, :destroy]
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_access, only: [:edit, :update, :destroy]

    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    def show
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:success] = "Article was successfully created."
            redirect_to article_path(@article)
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @article.update(article_params)
            flash[:success] = "Article was successfully updated."
            redirect_to article_path(@article)
        else
            render :new
        end
    end

    def destroy 
        @article.destroy
        flash[:success] = "Article was successfully deleted."
        redirect_to articles_path
    end

    private
        def set_article
            @article = Article.find(params[:id])
        end

        def article_params
            params.require(:article).permit(:title, :description)
        end

        def require_access
            if @article.user != current_user and !current_user.admin?
                flash[:danger] = "You can only edit your own articles."
                redirect_to article_path(@article)
            end
        end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    def index
        @categories = Category.all
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:success] = "Category was created."
            redirect_to categories_path
        else
            render 'new'
        end
    end

    def show
    end

    private
        def category_params
            params.require(:category).permit(:name)
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
        redirect_to articles_path if logged_in?
    end

    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:session][:email])
        if !user
            flash.now[:danger] = "Email not registered."
            render 'new'
        elsif user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash.now[:success] = "You have logged in."
            redirect_to user_path(user)
        else 
            flash.now[:danger] = "Incorrect password."
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "You have logged out."
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :require_user, only: [:edit, :update, :destroy]
    before_action :set_user, only: [:edit, :update, :show, :destroy]
    before_action :require_access, only: [:edit, :update]
    before_action :require_admin, only: [:destroy]

    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end

    def show
        @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Welcome to the Alpha Blog #{@user.username}."
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @user.update(user_params)
            flash[:success] = "Your account was successfully updated."
            redirect_to articles_path
        else 
            redirect_to 'edit'
        end
    end

    def destroy
        @user.destroy
        flash[:success] = "User has been deleted with all created articles."
        redirect_to users_path
    end

    private 
        def user_params
            params.require(:user).permit(:username, :email, :password)
        end

        def set_user
            @user = User.find(params[:id])
        end

        def require_access
            if @user != current_user or !current_user.admin?
                flash[:danger] = "You can only edit your own account."
                redirect_to user_path(current_user)
            end
        end

        def require_admin
            if !current_user.admin?
                flash[:danger] = "You must be admin to perform this action."
                redirect_to users_path
            end
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user, options = {size: 80})
		gravatar_id = Digest::MD5::hexdigest(user.email)
		size = options[:size]
		gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: "img-circle")
	end
end

app/views/articles/_articles.html.erb
<% articles.each do |article| %>
    <div class="well">
        <div class="article-header">
            <h2 class="article-title">
                <%= link_to article.title, article_path(article) %>
            </h2>
        </div>
        <div class="article-body">
            <h4><%= truncate(article.description, :length => 100) %></h4>
            <small class="article-details">
                Created by: <%= link_to article.user.username, user_path(article.user) %>,
                            <%= time_ago_in_words(article.created_at) %> ago.
                Last updated: <%= time_ago_in_words(article.updated_at) %> ago.
            </small>
        </div>
        <% if logged_in? and (article.user == current_user or current_user.admin?) %>
            <div class="article-actions">
                <%= link_to "Edit", edit_article_path(article), 
                    class: "btn btn-md btn-primary" %>
                <%= link_to "Delete", article_path(article), 
                    method: :delete, 
                    data: {confirm: "Are you sure you want to delete this article?"},
                    class: "btn btn-md btn-danger" %>
            </div>
        <% end %>
    </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
    <div class="col-sm-12">
        <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :title %>
                </div>
                <div class="col-sm-10">
                    <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :description %>
                </div>
                <div class="col-sm-10">
                    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-1 col-sm-offset-2">
                    <%= f.submit class: "btn btn-primary btn-lg" %>
                </div>
            </div>
        <% end %>

        <div class="col-sm-4 col-sm-offset-4" align="center">
            [ <%= link_to "Back to articles list", articles_path %> ]
        </div>
    </div>
</div>

app/views/articles/edit.html.erb
<div class="row">
    <div class="col-sm-10 col-sm-offset-2">
        <h1 class="page-title">Edit existing Article.</h1>
    </div>
</div>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="page-title">Articles</h1>

<div class="center">
    <%= will_paginate %>
</div>
<%= render 'articles', articles: @articles %>
<div class="center">
    <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<div class="row">
    <div class="col-sm-10 col-sm-offset-2">
        <h1 class="page-title">Create an Article</h1>
    </div>
</div>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="row">
    <div class="col-sm-12">
        <h1 class="page-title"><%= @article.title %></h1>
    </div>
</div>
<div class="well">
    <div class="row description">
        <div class="col-sm-2">
            <h3>Description:</h3>
        </div>
        <div class="col-sm-10">
            <h3><%= simple_format @article.description %></h3>
        </div>
    </div>
    <div class="row">
        <div class="article-actions col-sm-12">
            <% if logged_in? and @article.user == current_user %>
                <%= link_to "Edit", edit_article_path(@article), 
                    class: "btn btn-md btn-primary" %>
                <%= link_to "Delete", article_path(@article), 
                    method: :delete, 
                    data: {confirm: "Are you sure you want to delete this article?"},
                    class: "btn btn-md btn-danger" %>
            <% end %>
                <%= link_to "View all Articles", articles_path, 
                    class: "btn btn-md btn-success" %>
        </div>
    </div>
</div>

app/views/categories/index.html.erb
<h1 class="page-title">Categories</h1>
<% @categories.each do |category| %>
    <div class="row">
        <div class="col-sm-4 col-sm-offset-4">
            <div class="well center">
                <h3>
                    <%= link_to category.name.capitalize, category_path(category) %>
                </h3>
            </div>
        </div>
    </div>
<% end %>

app/views/categories/new.html.erb
<div class="row">
    <div class="col-sm-10 col-sm-offset-2">
        <h1 class="page-title">Create New Category</h1>
    </div>
</div>

<%= render 'shared/errors', obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :name %>
        </div>
        <div class="col-sm-10">
            <%= f.text_field :name, class: "form-control", placeholder: "Enter category name", autofocus: true %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-1 col-sm-offset-2">
            <%= f.submit "Create Category", class: "btn btn-primary btn-lg" %>
        </div>
    </div>
<% end %>

<div class="col-sm-4 col-sm-offset-4" align="center">
    [ <%= link_to "Back to articles list", articles_path %> ]
</div>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>
            Copyright &copy; <a href="http://www.example.com">Example Inc.</a>
            by <a href="http://www.brettclark.com">Brett Clark</a>
        </small>
        <nav>
            <ul>
                <li><%= link_to "About", about_path %></li>
            </ul>
        </nav>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<% if flash != nil %>
    <div class="container">
        <% flash.each do |name, msg| %>
            <div class="alert alert-<%= name %>">
                <a href="#" class="close" data-dismiss="alert">&#215</a>
                <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
            </div>
        <% end %>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Ruby Blog", root_path, id: "logo", class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Article", new_article_path %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Profile <%= "(Admin)" if current_user.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "View my profile", user_path(current_user) %></li>
              <li><%= link_to "Edit my profile", edit_user_path(current_user) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>RubyBlog</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
        <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page.</h1>

app/views/pages/home.html.erb
<div class="jumbotron center">
    <h1>RUBY BLOG</h1>
    <%= link_to "Sign up now", signup_path, class: "btn btn-danger btn-lg btn-xlarge" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="col-sm-10 col-sm-offset-2">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <%= pluralize(obj.errors.count, "error") %>
                        prohibited this article from being saved:
                    </h2>
                    <div class="panel-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg| %>
                                <li><%= msg %>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :username %>
        </div>
        <div class="col-sm-10">
            <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
        </div>
    </div>
    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :email %>
        </div>
        <div class="col-sm-10">
            <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
        </div>
    </div>
    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :password %>
        </div>
        <div class="col-sm-10">
            <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-1 col-sm-offset-2">
            <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-primary btn-lg") %>
        </div>
    </div>
<% end %>

<div class="col-sm-4 col-sm-offset-4" align="center">
    [ <%= link_to "Back to articles list", articles_path %> ]
</div>

app/views/users/edit.html.erb
<h1 class="page-title">Edit Account Details</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="page-title">Ruby Bloggers</h1>
<% @users.each do |user| %>
	<%= will_paginate %>
	<div class="user well">
		<div class="row">
			<div class="col-sm-2 icon">
				<%= link_to gravatar_for(user), user_path(user) %>
			</div>
			<div class="col-sm-10 details">
				<div class="name">
					<h2><%= link_to user.username, user_path(user) %></h2>
					<% if logged_in? and current_user.admin? %>
						<%= link_to "Delete this user?", user_path(user), class: "btn btn-sm btn-danger", method: :delete, data: {confirm: "Are you sure you want to delete this user all their articles?"} %>
					<% end %>
				</div>
				<span><%= pluralize(user.articles.count, "article") %></span>
			</div>
		</div>
	</div>
	<%= will_paginate %>
<% end %>

app/views/users/new.html.erb
<h1>Signup for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="page-title">Welcome to <%= @user.username %>'s page.</h1>
<div class="row">
	<div class="col-sm-4 col-sm-offset-4">
		<%= gravatar_for @user, size: 160 %>
	</div>
</div>
<h4><%= @user.username %>'s Articles.</h4>
<div class="center">
    <%= will_paginate @user_articles %>
</div>
<%= render 'articles/articles', articles: @user_articles %>
<div class="center">
    <%= will_paginate @user_articles%>
</div>